spring: 
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        auto-time-requests: false
    
logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/zipkin

---
spring:
  profiles: dev
  application:
    name: zipkin
    
server:
  port: 9006
  
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: zipkin-01
    prefer-ip-address: true