spring: 
  profiles:
    active: dev
  application:
    name: provider-dept
  jackson:
    default-property-inclusion: non-null

server:
  port: 8001
  tomcat:
      uri-encoding: UTF-8
      
management:
  security:
    enabled: false

logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/provider-dept

info: 
  app.name: microservice-springcloud
  company.name: https://spring.io/projects/spring-cloud
    
---
spring:
  profiles: dev
  zipkin:
    base-url: http://127.0.0.1:9006/
  sleuth:
    sampler:
      probability: 1.0  # springboot 2.x
      
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: provider-dept-01
    prefer-ip-address: true
    metadata-map:
      group: springcloud-group
      version: ${server.port}
              
---
spring:
  profiles: test
    
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka-01:7001/eureka/,http://eureka-02:7001/eureka/
  instance:
    instance-id: ${instanceId}
    prefer-ip-address: true
    metadata-map:
      group: springcloud-group
      version: ${server.port}